---
- name: Complete install
  hosts: localhost
  vars_file:
    - vars/main.yml

  tasks:
    - name: Install console tools
      include_tasks: console_tools.yml

    - name: Install softwares
      include_tasks: softwares.yml
