# Install Oh my ZSH
- name: Check that oh-my-zsh is not installed
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_check

- name: Downloading oh-my-zsh script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh
  when: not ohmyzsh_check.stat.exists

- name: Install oh-my-zsh
  command: sh /tmp/install_ohmyzsh.sh
  when: not ohmyzsh_check.stat.exists

# Install NerdFonts
- name: Check if the Font is already installed
  stat:
    path: ~/Library/Fonts/FiraCodeNerdFont-Bold.ttf # One of the many font available in the archive
  register: firaCodeFont_check

- name: Download the font from the repository
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
    dest: /tmp/FiraCode.zip
  when: not firaCodeFont_check.stat.exists

- name: Install font
  unarchive:
    src: /tmp/FiraCode.zip
    dest: ~/Library/Fonts
    remote_src: yes
  when: not firaCodeFont_check.stat.exists

# Install the Spaceship theme
- name: Check if spaceship-prompt theme is already installed
  stat:
    path: "~/.oh-my-zsh/custom/themes/spaceship-prompt"
  register: spaceshipTheme_check

- name: Downloading spaceship theme
  command: git clone https://github.com/spaceship-prompt/spaceship-prompt.git "~/.oh-my-zsh/custom/themes/spaceship-prompt" --depth=1
  when: not spaceshipTheme_check.stat.exists

- name: Link theme to ZSH
  file:
    src: "~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "~/.oh-my-zsh/custom/theme/spaceship.zsh-theme"
    state: link
  when: not spaceshipTheme_check.stat.exists

- name: Changer le thème ZSH en "spaceship" dans .zshrc
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="spaceship"'
    backrefs: yes
  when: not spaceshipTheme_check.stat.exists

# Install Homebrew
- name: Download Homebrew install script
  get_url:
    url: https://github.com/Homebrew/brew/releases/download/4.3.24/Homebrew-4.3.24.pkg
    dest: /tmp/install_Homebrew.pkg

- name: Install Homebrew
  command: installer -pkg /tmp/install_Homebrew.pkg -target /
  become: true

# aws-vault
- name: Install aws-vault
  community.general.homebrew_cask:
    name: aws-vault
    state: present

# jq
- name: Install jq
  community.general.homebrew:
    name: jq
    state: present

# AWS CLI
- name: Download aws-cli v2 .pkg file
  get_url:
    url: https://awscli.amazonaws.com/AWSCLIV2.pkg
    dest: /tmp/AWSCLIV2.pkg

- name: Install aws-cli v2
  command: installer -pkg /tmp/AWSCLIV2.pkg -target /
  become: true

# Install nvm
- name: Download nvm script
  # TODO : Voir si on peut avoir la last plutôt qu'une valeur en dure
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh
    dest: /tmp/install_nvm.sh

- name: Install nvm script
  command: sh /tmp/install_nvm.sh

# Install sdkman
- name: Download sdkman
  get_url:
    url: https://get.sdkman.io
    dest: /tmp/install_sdkman.sh

- name: Install sdkman
  command: sh /tmp/install_sdkman.sh

# Install pyenv
- name: Install pyenv
  community.general.homebrew:
    name: pyenv
