#!/usr/bin/env bash
# Install nvm (Node Version Manager)

set -e

echo "🔧 Installing nvm (Node Version Manager)..."

# Check if already installed
if [[ -d "$HOME/.nvm" ]]; then
  echo "✅ nvm already installed"

  # Source nvm to display version
  export NVM_DIR="$HOME/.nvm"
  if [[ -s "$NVM_DIR/nvm.sh" ]]; then
    source "$NVM_DIR/nvm.sh"
    nvm --version
  fi

  exit 0
fi

# Get latest nvm version
echo "📦 Fetching latest nvm version..."
NVM_VERSION=$(curl -s https://api.github.com/repos/nvm-sh/nvm/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

if [[ -z "$NVM_VERSION" ]]; then
  echo "⚠️  Could not fetch latest nvm version, using fallback v0.40.1"
  NVM_VERSION="v0.40.1"
else
  echo "   Latest version: $NVM_VERSION"
fi

# Download and install nvm
echo "📥 Downloading and installing nvm $NVM_VERSION..."
if ! curl -fsSL "https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh" | bash; then
  echo "❌ Failed to download or install nvm"
  echo "   Please check your internet connection and try again"
  exit 1
fi

echo "✅ nvm installed successfully"

# Create modular shell config for nvm
DOTFILES_DIR="$HOME/.dotfiles"
mkdir -p "$DOTFILES_DIR"

NVM_CONFIG="$DOTFILES_DIR/nvm.zsh"
cat > "$NVM_CONFIG" <<'EOF'
# ============================================================
# nvm (Node Version Manager) Configuration
# ============================================================
# Auto-generated by nvm-install.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
EOF

echo "✅ Created modular shell config: $NVM_CONFIG"
