#!/usr/bin/env bash
# Set up pyenv shell configuration

set -e

echo "🔧 Setting up pyenv configuration..."

# Check if pyenv is installed
if ! command -v pyenv &>/dev/null; then
  echo "⚠️  pyenv not found, skipping setup"
  exit 0
fi

echo "✅ pyenv found: $(pyenv --version)"

# Create modular shell config for pyenv
DOTFILES_DIR="$HOME/.dotfiles"
mkdir -p "$DOTFILES_DIR"

PYENV_CONFIG="$DOTFILES_DIR/pyenv.zsh"
cat > "$PYENV_CONFIG" <<'EOF'
# ============================================================
# pyenv (Python Version Manager) Configuration
# ============================================================
# Auto-generated by pyenv-setup.sh

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

# pyenv-virtualenv initialization
if command -v pyenv-virtualenv-init &>/dev/null; then
  eval "$(pyenv virtualenv-init -)"
fi
EOF

echo "✅ Created modular shell config: $PYENV_CONFIG"
