#!/usr/bin/env bash
# Install SDKMAN (Software Development Kit Manager for JVM)

set -e

echo "🔧 Installing SDKMAN..."

# Check if already installed
if [[ -d "$HOME/.sdkman" ]]; then
  echo "✅ SDKMAN already installed"

  # Source SDKMAN to display version
  if [[ -f "$HOME/.sdkman/bin/sdkman-init.sh" ]]; then
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk version
  fi

  exit 0
fi

# Download and install SDKMAN
echo "📦 Downloading and installing SDKMAN..."
if ! curl -fsSL "https://get.sdkman.io" | bash; then
  echo "❌ Failed to download or install SDKMAN"
  echo "   Please check your internet connection and try again"
  exit 1
fi

echo "✅ SDKMAN installed successfully"

# Create modular shell config for SDKMAN
DOTFILES_DIR="$HOME/.dotfiles"
mkdir -p "$DOTFILES_DIR"

SDKMAN_CONFIG="$DOTFILES_DIR/sdkman.zsh"
cat > "$SDKMAN_CONFIG" <<'EOF'
# ============================================================
# SDKMAN (Software Development Kit Manager) Configuration
# ============================================================
# Auto-generated by sdkman-install.sh

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
EOF

echo "✅ Created modular shell config: $SDKMAN_CONFIG"
